# Generated by Django 3.2 on 2022-03-15 01:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
            ],
            options={
                'unique_together': {('first_name', 'last_name')},
            },
        ),
        migrations.CreateModel(
            name='PlayerRating',
            fields=[
                ('player', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='leaderboard.player')),
                ('rating', models.IntegerField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winning_score', models.IntegerField(default=None)),
                ('losing_score', models.IntegerField(default=None)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('loser', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='lost_matches', to='leaderboard.player')),
                ('winner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='won_matches', to='leaderboard.player')),
            ],
        ),
    ]
